FinalProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('organization_manager.urls')),
    path('organization_manager/', include('organization_manager.urls')),
    path('admin/', admin.site.urls),
]

organization_manager/urls.py
from django.urls import path
from . import views

app_name = 'organization_manager'
urlpatterns = [
    path('', views.people, name='index'),
    path('people/filter/<int:household_ID>/', views.people_in_household, name='people_in_household'),
    path('people/', views.people, name='people'),
    path('person/<int:person_ID>/', views.person_form, name='update_person'),
    path('households/', views.households, name='households'),
    path('households/filter/<int:org_ID>/', views.households_in_org, name='households_in_org'),
    path('household/<int:household_ID>/', views.household_form, name='update_household'),
    path('organizations/', views.organizations, name='organizations'),
    path('organization/<int:org_ID>/', views.organization_form, name='update_organization')
]
#    path('person/<int:pk>/', views.PersonDetailView.as_view(), name='person_detail'),
#    path('person/<int:person_ID>/', views.person_form, name='update_person'),
#    path('household/<int:pk>/', views.HouseholdDetailView.as_view(), name='household_detail'),
#    path('organization/<int:pk>/', views.OrganizationDetailView.as_view(), name='organization_detail'),

organization_manager/models.py
from django.db import models

# Create your models here.


class Organization(models.Model):
    org_ID = models.AutoField(primary_key=True)
    organization_name = models.CharField(max_length=80, null=False)
    organization_description = models.TextField(null=True, blank=True)
    member_households = models.ManyToManyField('Household', blank=True)

    def __str__(self):
        return self.organization_name

    def get_info(self):
        return f"""
                Organization: {self.org_ID}
                Name: {self.organization_name}
                Description: {self.organization_description}
                """

    def get_members(self):
        return [household for household in self.member_households.all()]


class Household(models.Model):
    household_ID = models.AutoField(primary_key=True)
    household_name = models.CharField(max_length=20, default='household_ID', null=False)
    household_contact = models.ForeignKey('Person', related_name='contact_person', on_delete=models.SET_NULL,
                                          null=True, blank=True)
    members = models.ManyToManyField('Person', blank=True)
    address = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.household_ID)

    def get_info(self):
        out = f"""
                Household ID: {self.household_ID}
                Organizations: {[org.organization_name for org in self.organization_set]}
                Household Contact: {self.household_contact}
                Address: {self.address}
                """
        return out

    def get_members(self):
        return [member for member in Household.members.all().filter(id=self.household_ID)]


class Person(models.Model):
    person_ID = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=20, null=False)
    middle_name = models.CharField(max_length=20, default="", null=True, blank=True)
    last_name = models.CharField(max_length=20, null=False)
    email = models.EmailField(default=None, null=True, blank=True)
    spouse = models.ForeignKey('Person', default=None, on_delete=models.SET_NULL, null=True, blank=True)
    house = models.ForeignKey('Household', default=None, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.get_full_name()}"

    def get_info(self):
        out = f"""
                Person ID: {self.person_ID}
                Name: {self.get_full_name()}
                Email: {self.email}
                """
        if self.is_married():
            out += f"Spouse: {self.spouse}"

        return out

    def get_middle_name(self):
        return self.middle_name if self.middle_name else "-"

    def get_middle_name_or_blank(self):
        return self.middle_name if self.middle_name else ""

    def get_full_name(self):
        return f"{self.first_name} {self.middle_name if self.middle_name else ""} {self.last_name}"

    def get_spouse(self):
        return self.spouse if self.is_married() else "-"

    def get_email(self):
        return self.email if self.email else "-"

    def get_email_or_blank(self):
        return self.email if self.email else ""

    def is_married(self):
        return self.spouse is not None

    def get_household(self):
        return self.household_set

organization_manager/forms.py
from django import forms
from .models import Person, Household, Organization


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'middle_name', 'last_name', 'email', 'spouse', 'house']


class HouseholdForm(forms.ModelForm):
    class Meta:
        model = Household
        fields = ['household_name', 'household_contact', 'members', 'address']


class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ['organization_name', 'organization_description', 'member_households']

organization_manager/views.py
from django.db.models import F
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.template import loader

from .models import Person, Organization, Household
from .forms import PersonForm, HouseholdForm, OrganizationForm


# Create your views here.

def people(request):
    context = {}
    form = PersonForm()
    person_list = Person.objects.all()
    context['people'] = person_list
    context['title'] = 'People Database'

    if request.method == 'GET':
        if 'search' in request.GET:
            query = request.GET.get('search')
            print(query)
            household_list = Household.objects.all().filter(pk=query)

            if len(household_list) == 0:
                context['error'] = 'Household not found'
            elif len(household_list) > 1:
                context['error'] = 'Too many households match'
            else:
                household_ID = household_list[0].household_ID
                return HttpResponseRedirect(f'/organization_manager/people/filter/{household_ID}/')

    if request.method == 'POST':
        if 'save' in request.POST:
            form = PersonForm(request.POST)
            form.save()
            form = PersonForm()
        elif 'delete' in request.POST:
            pid = request.POST.get('delete')
            person = Person.objects.get(person_ID=pid)
            person.delete()
        elif 'edit' in request.POST:
            pid = request.POST.get('edit')
    context['form'] = form
    return render(request, "organization_manager/people.html", context)

def people_in_household(request, household_ID):
    context = {}
    form = HouseholdForm()
    household_list = Household.objects.all().filter(pk=household_ID)
    if len(household_list) == 0:
        return HttpResponseRedirect('/organization_manager/people')
    household = household_list[0]
    person_list = Person.objects.filter(household__in=household_list)
    person_excluded_list = Person.objects.exclude(household__in=household_list)
    context['people'] = person_list
    context['people_ex'] = person_excluded_list
    context['title'] = 'People By Household'
    context['household'] = household

    if request.method == 'POST':
        if 'add' in request.POST:
            pid = request.POST.get('add')
            person = Person.objects.get(pk=pid)
            household.members.add(person)
            household.save()
        elif 'remove' in request.POST:
            pid = request.POST.get('remove')
            person = Person.objects.get(pk=pid)
            household.members.remove(person)
            household.save()
        elif 'edit' in request.POST:
            pid = request.POST.get('edit')
    context['form'] = form
    return render(request, "organization_manager/house-people.html", context)

def person_form(request, person_ID=0):
    context = {}

    context['title'] = 'Edit Person'
    context['person_ID'] = person_ID
    context['people'] = Person.objects.all()
    context['households'] = Household.objects.all()

    if request.method == 'GET':
        if person_ID == 0:
            form = PersonForm()
        else:
            person = Person.objects.get(pk=person_ID)
            context['person'] = person
            form = PersonForm(instance=person)
            context['form'] = form
            return render(request, 'organization_manager/person.html', context)
    elif request.method == 'POST':
        person = Person.objects.get(pk=person_ID)
        form = PersonForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/organization_manager/people')

def households(request):
    context = {}
    form = HouseholdForm()
    household_list = Household.objects.all()
    context['households'] = household_list
    context['title'] = 'Household Database'

    if request.method == 'GET':
        if 'search' in request.GET:
            query = request.GET.get('search')
            print(query)
            organization_list = Organization.objects.all().filter(pk=query)

            if len(organization_list) == 0:
                context['error'] = 'Organization not found'
            elif len(organization_list) > 1:
                context['error'] = 'Too many organizations match'
            else:
                organization_ID = organization_list[0].org_ID
                return HttpResponseRedirect(f'/organization_manager/households/filter/{organization_ID}/')

    if request.method == 'POST':
        if 'save' in request.POST:
            form = HouseholdForm(request.POST)
            form.save()
            form = HouseholdForm()
        elif 'delete' in request.POST:
            hid = request.POST.get('delete')
            person = Household.objects.get(household_ID=hid)
            person.delete()
        elif 'edit' in request.POST:
            hid = request.POST.get('edit')
    context['form'] = form
    return render(request, "organization_manager/households.html", context)

def households_in_org(request, org_ID):
    context = {}
    form = HouseholdForm()
    organization_list = Organization.objects.all().filter(pk=org_ID)
    if len(organization_list) == 0:
        return HttpResponseRedirect('/organization_manager/households')
    organization = organization_list[0]
    context['title'] = f'Households By Organization'
    context['organization'] = organization

    if request.method == 'POST':
        if 'add' in request.POST:
            hid = request.POST.get('add')
            household = Household.objects.get(pk=hid)
            organization.member_households.add(household)
            organization.save()
        elif 'remove' in request.POST:
            hid = request.POST.get('remove')
            household = Household.objects.get(pk=hid)
            organization.member_households.remove(household)
            organization.save()
        elif 'edit' in request.POST:
            hid = request.POST.get('edit')
    household_list = Household.objects.filter(organization__in=organization_list)
    if len(household_list) == 0:
        return HttpResponseRedirect('/organization_manager/households')
    household_excluded_list = Household.objects.exclude(organization__in=organization_list)
    context['households'] = household_list
    context['households_ex'] = household_excluded_list
    context['form'] = form
    return render(request, "organization_manager/org-households.html", context)

def household_form(request, household_ID):
    context = {}

    context['title'] = 'Edit Household'
    context['household_ID'] = household_ID
    context['households'] = Household.objects.all()
    context['organizations'] = Organization.objects.all()

    if request.method == 'GET':
        if household_ID == 0:
            form = HouseholdForm()
        else:
            household = Household.objects.get(pk=household_ID)
            context['household'] = household
            form = HouseholdForm(instance=household)
            context['form'] = form
            return render(request, 'organization_manager/household.html', context)
    elif request.method == 'POST':
        household = Household.objects.get(pk=household_ID)
        form = HouseholdForm(request.POST, instance=household)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/organization_manager/households')

def organizations(request):
    context = {}
    form = OrganizationForm()
    organization_list = Organization.objects.all()
    context['organizations'] = organization_list
    context['title'] = 'Organization Database'

    if request.method == 'POST':
        if 'save' in request.POST:
            form = OrganizationForm(request.POST)
            form.save()
            form = OrganizationForm()
        elif 'delete' in request.POST:
            oid = request.POST.get('delete')
            selected_organization = Organization.objects.get(org_ID=oid)
            selected_organization.delete()
        elif 'edit' in request.POST:
            oid = request.POST.get('edit')
    context['form'] = form
    return render(request, "organization_manager/organizations.html", context)


def organization_form(request, org_ID):
    context = {}

    context['title'] = 'Edit Organization'
    context['organization_ID'] = org_ID
    context['households'] = Household.objects.all()
    context['organizations'] = Organization.objects.all()

    if request.method == 'GET':
        if org_ID == 0:
            form = OrganizationForm()
        else:
            organization = Organization.objects.get(pk=org_ID)
            context['organization'] = organization
            form = OrganizationForm(instance=organization)
            context['form'] = form
            return render(request, 'organization_manager/organization.html', context)
    elif request.method == 'POST':
        organization = Organization.objects.get(pk=org_ID)
        form = OrganizationForm(request.POST, instance=organization)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/organization_manager/organizations')

class IndexView(generic.ListView):
    template_name = 'organization_manager/index.html'
    context_object_name = 'person_list'

    def get_queryset(self):
        return Person.objects.all()


class PersonDetailView(generic.DetailView):
    model = Person
    template_name = 'organization_manager/person.html'


class HouseholdDetailView(generic.DetailView):
    model = Household
    template_name = 'organization_manager/household.html'


class OrganizationDetailView(generic.DetailView):
    model = Organization
    template_name = 'organization_manager/organization.html'

organization_manager/templates/organization_manager/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>


<nav class="navbar bg-dark navbar-expand-lg">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'organization_manager:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'organization_manager:people' %}">People</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'organization_manager:households' %}">Households</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'organization_manager:organizations' %}"> Organizations</a>
            </li>
        </ul>
    </div>
    {% block searchbar %}
    {% endblock searchbar %}
</nav>
<div class="container rounded py-5 bg-light">
    {% block content_header %}
    {% endblock content_header %}
    <hr class="my-5">
    {% block content %}
    {% endblock content %}
</div>

</body>
</html>

organization_manager/templates/organization_manager/house-people.html
{% extends 'organization_manager/base.html' %}

{% block title %}Person Database{% endblock title %}

{% block content_header %}
    <h1>People In Household: {{ household }}</h1>
{% endblock content_header %}

{% block content %}
    <form method="POST" action="{% url 'organization_manager:people_in_household' household.household_ID %}">
    {% csrf_token %}
        <table class="table table-striped">
            <tr>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Spouse</th>
                <th>Action</th>
            </tr>
            {% for person in people %}
                <tr>
                    <td class="align-middle">{{ person.first_name }}</td>
                    <td class="align-middle">{{ person.middle_name }}</td>
                    <td class="align-middle">{{ person.last_name }}</td>
                    <td class="align-middle">{{ person.email }}</td>
                    <td class="align-middle">{{ person.spouse }}</td>
                    <td class="align-middle">
                        <div class="d-flex gap-2">
                            <div class="p-1">
                                <a href="{% url 'organization_manager:update_person' person.person_ID %}" class="btn btn-primary">Edit</a>
                            </div>
                            <div class="p-1">
                                <button formnovalidate type="submit" class="btn btn-primary" name="remove" value="{{ person.person_ID }}">Remove</button>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <h1 class="py-5">Add a Person</h1>
        <hr>
        <table class="table table-striped">
            <tr>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Spouse</th>
                <th>Action</th>
            </tr>
            {% for person in people_ex %}
                <tr>
                    <td class="align-middle">{{ person.first_name }}</td>
                    <td class="align-middle">{{ person.middle_name }}</td>
                    <td class="align-middle">{{ person.last_name }}</td>
                    <td class="align-middle">{{ person.email }}</td>
                    <td class="align-middle">{{ person.spouse }}</td>
                    <td class="align-middle">
                        <div class="d-flex gap-2">
                            <div class="p-1">
                                <button formnovalidate type="submit" class="btn btn-primary" name="add" value="{{ person.person_ID }}">Add</button>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </form>
{% endblock content %}

organization_manager/templates/organization_manager/household.html
{% extends 'organization_manager/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update: {{ household.household_name }}{% endblock title %}

{% block content_header %}
    <h1>Edit Household</h1>
    <p><i>{{ household.household_name }}</i></p>
{% endblock content_header %}

{% block content %}
    <form method="POST" action="{% url 'organization_manager:update_household' household_ID %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary" name="update">Update</button>
    </form>
{% endblock content %}

organization_manager/templates/organization_manager/households.html
{% extends 'organization_manager/base.html' %}

{% block title %}Household Database{% endblock title %}

{% block content_header %}
    <h1>Households In Database</h1>
{% endblock content_header %}

{% block searchbar %}
    <form class="form-inline" method="GET">
        <div class="d-flex">
            <input class="form-control mr-sm2" type="text" placeholder="Search by Organization ID" name="search">
            <button type="submit" class="btn btn-primary my-2 my-sm-0">Search</button>
        </div>
    </form>
{% endblock searchbar %}

{% block content %}
    <form method="POST" action="{% url 'organization_manager:households' %}">
    {% csrf_token %}
        <table class="table table-striped">
            <tr>
                <th>Household ID</th>
                <th>Household Name</th>
                <th>Household Contact</th>
                <th>Number of Members</th>
                <th>Address</th>
                <th>Action</th>
            </tr>
            {% for household in households %}
                <tr>
                    <td class="align-middle">{{ household.household_ID }}</td>
                    <td class="align-middle">{{ household.household_name }}</td>
                    <td class="align-middle">{{ household.household_contact }}</td>
                    <td class="align-middle">{{ household.members.count }}</td>
                    <td class="align-middle">{{ household.address }}</td>
                    <td class="align-middle">
                        <div class="d-flex gap-2">
                            <div class="p-1">
                                <a href="{% url 'organization_manager:update_household' household.household_ID %}" class="btn btn-primary">Edit</a>
                            </div>
                            <div class="p-1">
                                <button formnovalidate type="submit" class="btn btn-primary" name="delete" value="{{ household.household_ID }}">Delete</button>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <h1 class="py-5">Add a Household</h1>
        <hr>
        <table class="table-striped">
            <tr>
                <th class="align-middle">Household Name</th>
                <th class="align-middle">Contact Person</th>
                <th class="align-middle">Members</th>
                <th class="align-middle">Address</th>
                <th class="align-middle">Action</th>
            </tr>
            <tr>
            {% for field in form %}
                <td class="align-middle">{{ field }}</td>
            {% endfor %}
                <td>
                    <div class="d-grid p-1 mx-auto"><button type="submit" class="btn btn-primary" name="save">Save</button></div>
                </td>
            </tr>
        </table>
    </form>
{% endblock content %}

organization_manager/templates/organization_manager/index.html
{% extends "organization_manager/base.html" %}

{% block content %}
{% endblock content %}

organization_manager/templates/organization_manager/org-households.html
{% extends 'organization_manager/base.html' %}

{% block title %}Household Database{% endblock title %}

{% block content_header %}
    <h1>Households In {{ organization }}</h1>
{% endblock content_header %}

{% block content %}
    <form method="POST" action="{% url 'organization_manager:households_in_org' organization.org_ID %}">
    {% csrf_token %}
        <table class="table table-striped">
            <tr>
                <th>Household Name</th>
                <th>Household Contact</th>
                <th>Number of Members</th>
                <th>Address</th>
                <th>Action</th>
            </tr>
            {% for household in households %}
                <tr>
                    <td class="align-middle">{{ household.household_name }}</td>
                    <td class="align-middle">{{ household.household_contact }}</td>
                    <td class="align-middle">{{ household.members.count }}</td>
                    <td class="align-middle">{{ household.address }}</td>
                    <td class="align-middle">
                        <div class="d-flex gap-2">
                            <div class="p-1">
                                <a href="{% url 'organization_manager:update_household' household.household_ID %}" class="btn btn-primary">Edit</a>
                            </div>
                            <div class="p-1">
                                <button formnovalidate type="submit" class="btn btn-primary" name="remove" value="{{ household.household_ID }}">Remove</button>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <h1 class="py-5">Add a Household</h1>
        <hr>
        <table class="table table-striped">
            <tr>
                <th>Household Name</th>
                <th>Household Contact</th>
                <th>Number of Members</th>
                <th>Address</th>
                <th>Action</th>
            </tr>
            {% for household in households_ex %}
                <tr>
                    <td class="align-middle">{{ household.household_name }}</td>
                    <td class="align-middle">{{ household.household_contact }}</td>
                    <td class="align-middle">{{ household.members.count }}</td>
                    <td class="align-middle">{{ household.address }}</td>
                    <td class="align-middle">
                        <div class="d-flex gap-2">
                            <div class="p-1">
                                <button formnovalidate type="submit" class="btn btn-primary" name="add" value="{{ household.household_ID }}">Add</button>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </form>
{% endblock content %}

organization_manager/templates/organization_manager/organizations.html
{% extends 'organization_manager/base.html' %}

{% block title %}Organization Database{% endblock title %}

{% block content_header %}
    <h1>Organizations In Database</h1>
{% endblock content_header %}

{% block content %}
    <form method="POST" action="{% url 'organization_manager:organizations' %}">
    {% csrf_token %}
        <table class="table table-striped">
            <tr>
                <th>Organization Name</th>
                <th>Organization Description</th>
                <th>Number of Households</th>
                <th>Actions</th>
            </tr>
            {% for organization in organizations %}
                <tr>
                    <td class="align-middle">{{ organization.organization_name }}</td>
                    <td class="align-middle">{{ organization.organization_description }}</td>
                    <td class="align-middle">{{ organization.member_households.count }}</td>
                    <td class="align-middle">
                        <div class="d-flex gap-2">
                            <div class="p-1">
                                <a href="{% url 'organization_manager:update_organization' organization.org_ID %}" class="btn btn-primary">Edit</a>
                            </div>
                            <div class="p-1">
                                <button formnovalidate type="submit" class="btn btn-primary" name="delete" value="{{ organization.organization_ID }}">Delete</button>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <h1 class="py-5">Add an Organization</h1>
        <hr>
        <table class="table table-striped">
            <tr>
                <th class="align-middle">Organization Name</th>
                <th class="align-middle">Description</th>
                <th class="align-middle">Households</th>
                <th class="align-middle">Action</th>
            </tr>
            <tr>
            {% for field in form %}
                <td>{{ field }}</td>
            {% endfor %}
                <td>
                    <div class="d-grid p-1 mx-auto"><button type="submit" class="btn btn-primary" name="save">Save</button></div>
                </td>
            </tr>
        </table>
    </form>
{% endblock content %}

organization_manager/templates/organization_manager/people.html
{% extends 'organization_manager/base.html' %}

{% block title %}People Database{% endblock title %}

{% block content_header %}
    <h1>People In Database</h1>
{% endblock content_header %}

{% block searchbar %}
    <form class="form-inline" method="GET">
        <div class="d-flex">
            <input class="form-control mr-sm2" type="text" placeholder="Search by household ID" name="search">
            <button type="submit" class="btn btn-primary my-2 my-sm-0">Search</button>
        </div>
    </form>
{% endblock searchbar %}

{% block content %}
    {% if error %}
        <p>{{ error }}</p>
    {% endif %}
    <form method="POST" action="{% url 'organization_manager:people' %}">
    {% csrf_token %}
        <table class="table table-striped">
            <tr>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Spouse</th>
                <th>Household</th>
                <th>Action</th>
            </tr>
            {% for person in people %}
                <tr>
                    <td class="align-middle">{{ person.first_name }}</td>
                    <td class="align-middle">{{ person.get_middle_name }}</td>
                    <td class="align-middle">{{ person.last_name }}</td>
                    <td class="align-middle">{{ person.get_email }}</td>
                    <td class="align-middle">{{ person.get_spouse }}</td>
                    <td class="align-middle">{{ person.house }}</td>
                    <td class="align-middle">
                        <div class="d-flex gap-2">
                            <div class="p-1">
                                <a href="{% url 'organization_manager:update_person' person.person_ID %}" class="btn btn-primary">Edit</a>
                            </div>
                            <div class="p-1">
                                <button formnovalidate type="submit" class="btn btn-primary" name="delete" value="{{ person.person_ID }}">Delete</button>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
                <tr>
                {% for field in form %}
                    <td class="align-middle">{{ field }}</td>
                {% endfor %}
                    <td>
                        <div class="d-grid p-1 mx-auto"><button type="submit" class="btn btn-primary" name="save">Save</button></div>
                    </td>
                </tr>
        </table>
    </form>
{% endblock content %}